In [46]:
import pandas as pd

In [47]:
data_dic = pd.read_csv("YRBS_2023_Data_Dictionary_Ordered.csv")

In [48]:
data_dic.head(20)

   Variable     Question_Description  Value            Value_Meaning
0        Q1          How old are you    1.0  12 years old or younger
1        Q1          How old are you    2.0             13 years old
2        Q1          How old are you    3.0             14 years old
3        Q1          How old are you    4.0             15 years old
4        Q1          How old are you    5.0             16 years old
5        Q1          How old are you    6.0             17 years old
6        Q1          How old are you    7.0    18 years old or older
7        Q2         What is your sex    1.0                   Female
8        Q2         What is your sex    2.0                     Male
9        Q3    In what grade are you    1.0                9th grade
10       Q3    In what grade are you    2.0               10th grade
11       Q3    In what grade are you    3.0               11th grade
12       Q3    In what grade are you    4.0               12th grade
13       Q3    In what grade are you    5.0  Ungraded or other grade
14       Q4  Are you Hispanic/Latino    1.0                      Yes
15       Q4  Are you Hispanic/Latino    2.0                       No
16       Q5        What is your race    NaN                      NaN
17       Q6         How tall are you    NaN                      NaN
18       Q7    How much do you weigh    NaN                      NaN
19       Q8            Seat belt use    1.0                    Never

In [49]:
raw_data = pd.read_csv('XXH2023_YRBS_Data.csv')
raw_data.head(5)

C:\Users\chawi\AppData\Local\Temp\ipykernel_28040\4010718000.py:1: DtypeWarning: Columns (0: Q92, 1: Q93, 2: Q94, 3: Q95, 4: Q96, 5: Q97, 6: Q98, 7: Q104, 8: Q105, 9: Q106, 10: Q107, 11: Q6ORIG) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_data = pd.read_csv('XXH2023_YRBS_Data.csv')

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16,Q17,Q18,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27,Q28,Q29,Q30,Q31,Q32,Q33,Q34,Q35,Q36,Q37,Q38,Q39,Q40,Q41,Q42,Q43,Q44,Q45,Q46,Q47,Q48,Q49,Q50,Q51,Q52,Q53,Q54,Q55,Q56,Q57,Q58,Q59,Q60,Q61,Q62,Q63,Q64,Q65,Q66,Q67,Q68,Q69,Q70,Q71,Q72,Q73,Q74,Q75,Q76,Q77,Q78,Q79,Q80,Q81,Q82,Q83,Q84,Q85,Q86,Q87,Q88,Q89,Q90,Q91,Q92,Q93,Q94,Q95,Q96,Q97,Q98,Q99,Q100,Q101,Q102,Q103,Q104,Q105,Q106,Q107,QN8,QN9,QN10,QN11,QN12,QN13,QN14,QN15,QN16,QN17,QN18,QN19,QN20,QN21,QN22,QN23,QN24,QN25,QN26,QN27,QN28,QN29,QN30,QN31,QN32,QN33,QN34,QN35,QN36,QN37,QN38,QN39,QN40,QN41,QN42,QN43,QN44,QN45,QN46,QN47,QN48,QN49,QN50,QN51,QN52,QN53,QN54,QN55,QN56,QN57,QN58,QN59,QN60,QN61,QN62,QN66,QN67,QN68,QN69,QN70,QN71,QN72,QN73,QN74,QN75,QN76,QN77,QN78,QN79,QN80,QN81,QN82,QN83,QN84,QN85,QN86,QN87,QN88,QN89,QN90,QN91,QN92,QN93,QN94,QN95,QN96,QN97,QN98,QN99,QN100,QN101,QN102,QN103,QN104,QN105,QN106,QN107,SITE,QNFRCIG,QNDAYCIG,QNFREVP,QNDAYEVP,QNFRSKL,QNDAYSKL,QNFRCGR,QNDAYCGR,QNTB2,QNTB3,QNTB4,QNTB5,QNIUDIMP,QNOTHHPL,QNDUALBC,QNBCNONE,QNFR0,QNFR1,QNFR2,QNVEG0,QNVEG1,QNVEG2,QNVEG3,QNSODA1,QNSODA2,QNBK7DAY,QNPA0DAY,QNPA7DAY,QNDLYPE,QNNODNT,QNSPDRK1,QNSPDRK2,QNWATER1,QNWATER2,QNWATER3,QNILLICT,QNOBESE,QNOWT,WEIGHT,STRATUM,PSU,BMIPCT,RACEETH,Q6ORIG,Q7ORIG
0,14 years old,Female,9th grade,NaN,C,1.65,81.65,Most of the time,4 or 5 times,Did not drive,Did not drive,0 days,0 days,2 or 3 days,0 times,0 times,0 times,No,No,0 times,0 times,0 times,Never,No,No,Yes,No,No,0 times,Did not attempt suicide,No,Never smoked a cigarette,0 days,Did not smoke cigarettes,No,0 days,Did not use EVP,0 days,0 days,Did not use tobacco products,Never drank alcohol,0 days,0 days,Did not drink in past 30 days,Did not drink in past 30 days,0 times,Never tried marijuana,0 times,1 or 2 times,0 times,0 times,0 times,NaN,0 times,0 times,No,Never had sex,Never had sex,Never had sex,Never had sex,Never had sex,Never had sex,Never had sexual contact,Gay or lesbian,No,Slightly underweight,Lose weight,1 to 3 times,4 to 6 times,Did not eat green salad,Did not eat potatoes,Did not eat carrots,Did not eat other vegetables,1 to 3 times,3 days,0 days,1 day,1 team,0 times,Several times a day,No,No,During the past 12 months,Never,6 hours,Home of parent or gaurdian,NaN,No,NaN,Never,Never,1 or 2 times,0 times,Never had sexual contact,4 to 6 times,4 to 6 times,0 days,2 times,Never,No,Yes,No,Not sure,Sometimes,No,No,Well,1.0,1.0,NaN,NaN,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,NaN,2.0,2.0,NaN,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,2.0,2.0,1.0,2.0,NaN,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,XX,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,1.0,2.0,0.8614,103,16294,97.08,NaN,505,180
1,15 years old,Male,9th grade,No,E,NaN,NaN,Always,0 times,Did not drive,Did not drive,0 days,0 days,0 days,0 times,1 time,1 time,No,No,0 times,0 times,0 times,Sometimes,Yes,No,No,No,No,0 times,Did not attempt suicide,No,Never smoked a cigarette,0 days,Did not smoke cigarettes,No,0 days,Did not use EVP,0 days,0 days,Did not use tobacco products,Never drank alcohol,0 days,0 days,Did not drink in past 30 days,Did not drink in past 30 days,0 times,Never tried marijuana,0 times,0 times,0 times,0 times,0 times,0 times,0 times,0 times,No,Never had sex,Never had sex,Never had sex,Never had sex,Never had sex,Never had sex,Never had sexual contact,Heterosexual (straight),No,Slightly overweight,Lose weight,Did not drink fruit juice,Did not eat fruit,Did not eat green salad,Did not eat potatoes,Did not eat carrots,Did not eat other vegetables,1 to 3 times,4 days,4 days,5 days,1 team,0 times,A few times a week,No,No,Between 12 and 24 months ago,Sometimes,8 hours,Home of parent or gaurdian,Mostly D's,No,Rarely,Rarely,Rarely,0 times,0 times,Never had sexual contact,4 to 6 times,4 or more times per day,7 days,1 time,Always,No,No,No,Agree,Always,No,Yes,Well,2.0,2.0,NaN,NaN,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,NaN,2.0,2.0,NaN,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,XX,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,NaN,NaN,0.8920,103,16294,NaN,White,N N,233
2,16 years old,Male,11th grade,No,E,1.68,74.84,Always,2 or 3 times,Did not drive when drinking,1 or 2 days,0 days,0 days,0 days,0 times,0 times,0 times,No,No,0 times,0 times,0 times,Never,No,No,Yes,No,No,0 times,Did not attempt suicide,Yes,13 or 14 years old,0 days,Did not smoke cigarettes,Yes,1 or 2 days,Friend or family,0 days,0 days,No,15 or 16 years old,0 days,0 days,Did not drink in past 30 days,Did not drink in past 30 days,0 times,Never tried marijuana,0 times,0 times,0 times,1 or 2 times,0 times,0 times,0 times,0 times,Yes,16 years old,3 people,1 person,No,Yes,Birth control pills,Females and males,Bisexual,No,Slightly overweight,Lose weight,4 to 6 times,1 to 3 times,Did not eat green salad,1 to 3 times,Did not eat carrots,1 to 3 times,1 time per day,7 days,7 days,3 days,0 teams,0 times,More than once an hour,No,No,During the past 12 months,Rarely,4 or less hours,Home of parent or gaurdian,Mostly C's,No,Sometimes,Rarely,Rarely,0 times,0 times,Yes,I did not drink,3 times per day,0 days,0 times,Always,No,No,Yes,Agree,Most of the time,No,No,Very well,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,XX,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,0.5081,103,16294,92.26,White,506,165
3,17 years old,Female,10th grade,No,E,NaN,NaN,Most of the time,0 times,Did not drive when drinking,All 30 days,0 days,0 days,2 or 3 days,0 times,0 times,0 times,No,Yes,0 times,0 times,0 times,Never,No,No,Yes,No,No,0 times,Did not attempt suicide,No,Never smoked a cigarette,0 days,Did not smoke cigarettes,Yes,All 30 days,Some other way,0 days,0 days,No,13 or 14 years old,1 or 2 days,0 days,1 or 2 drinks,Some other way,10 to 19 times,13 or 14 years old,1 or 2 times,0 times,0 times,1 or 2 times,0 times,0 times,0 times,0 times,Yes,14 years old,1 person,1 person,No,No,Birth control pills,Males,Heterosexual (straight),No,About the right weight,Gain weight,3 times per day,3 times per day,Did not eat green salad,Did not eat potatoes,Did not eat carrots,Did not eat other vegetables,2 times per day,0 days,2 days,5 days,1 team,0 times,More than once an hour,No,No,During the past 12 months,Sometimes,7 hours,Home of parent or gaurdian,Mostly C's,Yes,Never,Never,Never,0 times,0 times,Yes,2 times per day,4 or more times per day,0 days,0 times,Always,No,No,No,Disagree,Always,No,Yes,Very well,1.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,XX,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,1.1759,103,16294,NaN,White,N N,105
4,14 years old,Male,9th grade,No,E,1.85,56.70,Always,0 times,Did not drive,Did not drive,0 days,0 days,0 days,0 times,2 or 3 times,0 times,No,No,0 times,0 times,Did not date,Never,No,No,Yes,No,Yes,0 times,Did not attempt suicide,Yes,13 or 14 years old,0 days,Did not smoke cigarettes,Yes,0 days,Did not use EVP,3 to 5 days,0 days,No,13 or 14 years old,1 or 2 days,0 days,1 or 2 drinks,Bought in store,0 times,Never tried marijuana,0 times,0 times,0 times,0 times,0 times,0 times,0 times,0 times,Yes,14 years old,1 person,1 person,No,Yes,Condoms,Females,Heterosexual (straight),No,About the right weight,Stay the same weight,4 to 6 times,4 to 6 times,1 time per day,1 to 3 times,Did not eat carrots,1 to 3 times,4 to 6 times,2 days,7 days,0 days,0 teams,1 time,Several times a day,No,No,During the past 12 months,Sometimes,6 hours,Home of parent or gaurdian,Mostly D's,No,Never,Never,Never,0 times,0 times,No,1 to 3 times,3 times per day,7 days,2 times,Always,No,No,No,Agree,Always,No,No,Very well,2.0,2.0,NaN,NaN,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,NaN,1.0,2.0,NaN,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,XX,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,0.8920,103,16294,7.57,White,601,125

In [50]:
raw_data.columns

Index(['Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9', 'Q10',
       ...
       'QNILLICT', 'QNOBESE', 'QNOWT', 'WEIGHT', 'STRATUM', 'PSU', 'BMIPCT',
       'RACEETH', 'Q6ORIG', 'Q7ORIG'],
      dtype='str', length=250)

In [51]:
selected_columns = ['Q1', 'Q2', 'Q3', 'Q9', 'Q14', 'Q15', 'Q16', 'Q17', 'Q18', 'Q20', 
                    'Q23', 'Q24', 'Q25', 'Q26', 'Q27', 'Q41', 'Q42', 'Q43', 'Q44', 'Q76', 
                    'Q80', 'Q84', 'Q85', 'Q86', 'Q87', 'Q89', 'Q90', 'Q91', 'Q100', 'Q101', 
                    'Q102', 'Q103', 'Q104', 'Q105', 'Q106']
data = raw_data[selected_columns]
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 20103 entries, 0 to 20102
Data columns (total 35 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Q1      20005 non-null  str
 1   Q2      19945 non-null  str
 2   Q3      19910 non-null  str
 3   Q9      19598 non-null  str
 4   Q14     18982 non-null  str
 5   Q15     17974 non-null  str
 6   Q16     11652 non-null  str
 7   Q17     17460 non-null  str
 8   Q18     14577 non-null  str
 9   Q20     15752 non-null  str
 10  Q23     18286 non-null  str
 11  Q24     19902 non-null  str
 12  Q25     19898 non-null  str
 13  Q26     19863 non-null  str
 14  Q27     19667 non-null  str
 15  Q41     19248 non-null  str
 16  Q42     19202 non-null  str
 17  Q43     15441 non-null  str
 18  Q44     14414 non-null  str
 19  Q76     18876 non-null  str
 20  Q80     15203 non-null  str
 21  Q84     15705 non-null  str
 22  Q85     17441 non-null  str
 23  Q86     14541 non-null  str
 24  Q87     16535 non-null  str
 25  Q89     13920 non-null  str
 26  Q90     13917 non-null  str
 27  Q91     13753 non-null  str
 28  Q100    13227 non-null  str
 29  Q101    13305 non-null  str
 30  Q102    13342 non-null  str
 31  Q103    11177 non-null  str
 32  Q104    10850 non-null  str
 33  Q105    10583 non-null  str
 34  Q106    10946 non-null  str
dtypes: str(35)
memory usage: 5.4 MB

In [52]:
data.columns = ['age', 'gender', 'education_level', 'ride_drinking_driver', 
                'school_safety_concern', 'threatened_at_school', 'fight_count', 
                'school_fight_count', 'neighborhood_violence', 'sexual_violence', 
                'school_racism', 'school_bullying', 'cyber_bullying', 'feel_hopeless', 
                'considered_suicide', 'first_alcohol', 'alcohol_frequency', 
                'hardcore_alcohol_frequency', 'drinking_in_a_row', 'exercise', 
                'social_media', 'mental_health', 'hours_of_sleep', 'sleep_place', 
                'grade', 'parent_emotional_abuse', 'parent_physical_abuse', 
                'parent_abuse_parent', 'parent_uses_alcohol', 'parent_mental_illness', 
                'incarcerated_parent', 'have_friend', 'parent_monitoring', 
                'unfair_discipline_school', 'ADHD']

In [53]:
data

,age,gender,education_level,ride_drinking_driver,school_safety_concern,threatened_at_school,fight_count,school_fight_count,neighborhood_violence,sexual_violence,school_racism,school_bullying,cyber_bullying,feel_hopeless,considered_suicide,first_alcohol,alcohol_frequency,hardcore_alcohol_frequency,drinking_in_a_row,exercise,social_media,mental_health,hours_of_sleep,sleep_place,grade,parent_emotional_abuse,parent_physical_abuse,parent_abuse_parent,parent_uses_alcohol,parent_mental_illness,incarcerated_parent,have_friend,parent_monitoring,unfair_discipline_school,ADHD
0,14 years old,Female,9th grade,4 or 5 times,2 or 3 days,0 times,0 times,0 times,No,0 times,Never,No,No,Yes,No,Never drank alcohol,0 days,0 days,Did not drink in past 30 days,0 days,Several times a day,Never,6 hours,Home of parent or gaurdian,NaN,NaN,Never,Never,No,Yes,No,Not sure,Sometimes,No,No
1,15 years old,Male,9th grade,0 times,0 days,0 times,1 time,1 time,No,0 times,Sometimes,Yes,No,No,No,Never drank alcohol,0 days,0 days,Did not drink in past 30 days,4 days,A few times a week,Sometimes,8 hours,Home of parent or gaurdian,Mostly D's,Rarely,Rarely,Rarely,No,No,No,Agree,Always,No,Yes
2,16 years old,Male,11th grade,2 or 3 times,0 days,0 times,0 times,0 times,No,0 times,Never,No,No,Yes,No,15 or 16 years old,0 days,0 days,Did not drink in past 30 days,7 days,More than once an hour,Rarely,4 or less hours,Home of parent or gaurdian,Mostly C's,Sometimes,Rarely,Rarely,No,No,Yes,Agree,Most of the time,No,No
3,17 years old,Female,10th grade,0 times,2 or 3 days,0 times,0 times,0 times,No,0 times,Never,No,No,Yes,No,13 or 14 years old,1 or 2 days,0 days,1 or 2 drinks,2 days,More than once an hour,Sometimes,7 hours,Home of parent or gaurdian,Mostly C's,Never,Never,Never,No,No,No,Disagree,Always,No,Yes
4,14 years old,Male,9th grade,0 times,0 days,0 times,2 or 3 times,0 times,No,0 times,Never,No,No,Yes,No,13 or 14 years old,1 or 2 days,0 days,1 or 2 drinks,7 days,Several times a day,Sometimes,6 hours,Home of parent or gaurdian,Mostly D's,Never,Never,Never,No,No,No,Agree,Always,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20098,14 years old,Female,9th grade,0 times,0 days,1 time,NaN,0 times,No,1 time,Never,Yes,Yes,Yes,Yes,13 or 14 years old,0 days,NaN,Did not drink in past 30 days,1 day,I do not use social media,NaN,6 hours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20099,15 years old,Male,9th grade,0 times,0 days,0 times,NaN,0 times,Yes,NaN,Rarely,Yes,No,Yes,No,Never drank alcohol,0 days,NaN,Did not drink in past 30 days,5 days,More than once an hour,NaN,9 hours,NaN,Mostly C's,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20100,15 years old,Male,9th grade,0 times,0 days,0 times,NaN,0 times,No,0 times,Never,No,No,No,No,Never drank alcohol,0 days,NaN,Did not drink in past 30 days,4 days,I do not use social media,NaN,8 hours,NaN,Mostly A's,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20101,16 years old,Male,9th grade,0 times,0 days,0 times,NaN,0 times,No,0 times,Never,No,No,No,No,Never drank alcohol,0 days,NaN,Did not drink in past 30 days,4 days,More than once an hour,NaN,6 hours,NaN,Mostly D's,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20102,15 years old,Female,9th grade,0 times,0 days,0 times,NaN,0 times,No,0 times,Rarely,No,No,No,No,Never drank alcohol,0 days,NaN,Did not drink in past 30 days,5 days,Several times a day,NaN,4 or less hours,NaN,Mostly C's,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN