In [3]:
import pandas as pd
import numpy as np

In [4]:
data_dic = pd.read_csv("YRBS_2023_Data_Dictionary_Ordered.csv")

In [5]:
data_dic.head()

  Variable Question_Description  Value            Value_Meaning
0       Q1      How old are you    1.0  12 years old or younger
1       Q1      How old are you    2.0             13 years old
2       Q1      How old are you    3.0             14 years old
3       Q1      How old are you    4.0             15 years old
4       Q1      How old are you    5.0             16 years old

In [6]:
raw_data = pd.read_csv('XXH2023_YRBS_Data.csv')
raw_data.head(5)

C:\Users\chawi\AppData\Local\Temp\ipykernel_30352\4010718000.py:1: DtypeWarning: Columns (0: Q92, 1: Q93, 2: Q94, 3: Q95, 4: Q96, 5: Q97, 6: Q98, 7: Q104, 8: Q105, 9: Q106, 10: Q107, 11: Q6ORIG) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_data = pd.read_csv('XXH2023_YRBS_Data.csv')

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,...,QNILLICT,QNOBESE,QNOWT,WEIGHT,STRATUM,PSU,BMIPCT,RACEETH,Q6ORIG,Q7ORIG
0,14 years old,Female,9th grade,NaN,C,1.65,81.65,Most of the time,4 or 5 times,Did not drive,...,NaN,1.0,2.0,0.8614,103,16294,97.08,NaN,505,180
1,15 years old,Male,9th grade,No,E,NaN,NaN,Always,0 times,Did not drive,...,2.0,NaN,NaN,0.8920,103,16294,NaN,White,N N,233
2,16 years old,Male,11th grade,No,E,1.68,74.84,Always,2 or 3 times,Did not drive when drinking,...,1.0,2.0,1.0,0.5081,103,16294,92.26,White,506,165
3,17 years old,Female,10th grade,No,E,NaN,NaN,Most of the time,0 times,Did not drive when drinking,...,1.0,NaN,NaN,1.1759,103,16294,NaN,White,N N,105
4,14 years old,Male,9th grade,No,E,1.85,56.70,Always,0 times,Did not drive,...,2.0,2.0,2.0,0.8920,103,16294,7.57,White,601,125

In [7]:
raw_data.columns

Index(['Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9', 'Q10',
       ...
       'QNILLICT', 'QNOBESE', 'QNOWT', 'WEIGHT', 'STRATUM', 'PSU', 'BMIPCT',
       'RACEETH', 'Q6ORIG', 'Q7ORIG'],
      dtype='str', length=250)

In [8]:
selected_columns = ['Q1', 'Q2', 'Q3', 'Q9', 'Q14', 'Q15', 'Q16', 'Q17', 'Q18', 'Q20', 
                    'Q23', 'Q24', 'Q25', 'Q26', 'Q27', 'Q41', 'Q42', 'Q43', 'Q44', 'Q76', 
                    'Q80', 'Q84', 'Q85', 'Q86', 'Q87', 'Q89', 'Q90', 'Q91', 'Q100', 'Q101', 
                    'Q102', 'Q103', 'Q104', 'Q105', 'Q106']
data = raw_data[selected_columns]

In [9]:
data.columns = ['age', 'gender', 'education_level', 'ride_drinking_driver', 
                'school_safety_concern', 'threatened_at_school', 'fight_count', 
                'school_fight_count', 'neighborhood_violence', 'sexual_violence', 
                'school_racism', 'school_bullying', 'cyber_bullying', 'feel_hopeless', 
                'considered_suicide', 'first_alcohol', 'alcohol_frequency', 
                'hardcore_alcohol_frequency', 'drinking_in_a_row', 'exercise', 
                'social_media', 'mental_health', 'hours_of_sleep', 'sleep_place', 
                'grade', 'parent_emotional_abuse', 'parent_physical_abuse', 
                'parent_abuse_parent', 'parent_uses_alcohol', 'parent_mental_illness', 
                'incarcerated_parent', 'have_friend', 'parent_monitoring', 
                'unfair_discipline_school', 'ADHD']

In [10]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 20103 entries, 0 to 20102
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   age                         20005 non-null  str
 1   gender                      19945 non-null  str
 2   education_level             19910 non-null  str
 3   ride_drinking_driver        19598 non-null  str
 4   school_safety_concern       18982 non-null  str
 5   threatened_at_school        17974 non-null  str
 6   fight_count                 11652 non-null  str
 7   school_fight_count          17460 non-null  str
 8   neighborhood_violence       14577 non-null  str
 9   sexual_violence             15752 non-null  str
 10  school_racism               18286 non-null  str
 11  school_bullying             19902 non-null  str
 12  cyber_bullying              19898 non-null  str
 13  feel_hopeless               19863 non-null  str
 14  considered_suicide          19667 non-null  str
 15  first_alcohol               19248 non-null  str
 16  alcohol_frequency           19202 non-null  str
 17  hardcore_alcohol_frequency  15441 non-null  str
 18  drinking_in_a_row           14414 non-null  str
 19  exercise                    18876 non-null  str
 20  social_media                15203 non-null  str
 21  mental_health               15705 non-null  str
 22  hours_of_sleep              17441 non-null  str
 23  sleep_place                 14541 non-null  str
 24  grade                       16535 non-null  str
 25  parent_emotional_abuse      13920 non-null  str
 26  parent_physical_abuse       13917 non-null  str
 27  parent_abuse_parent         13753 non-null  str
 28  parent_uses_alcohol         13227 non-null  str
 29  parent_mental_illness       13305 non-null  str
 30  incarcerated_parent         13342 non-null  str
 31  have_friend                 11177 non-null  str
 32  parent_monitoring           10850 non-null  str
 33  unfair_discipline_school    10583 non-null  str
 34  ADHD                        10946 non-null  str
dtypes: str(35)
memory usage: 5.4 MB

In [11]:
data.isnull().sum()

age                             98
gender                         158
education_level                193
ride_drinking_driver           505
school_safety_concern         1121
threatened_at_school          2129
fight_count                   8451
school_fight_count            2643
neighborhood_violence         5526
sexual_violence               4351
school_racism                 1817
school_bullying                201
cyber_bullying                 205
feel_hopeless                  240
considered_suicide             436
first_alcohol                  855
alcohol_frequency              901
hardcore_alcohol_frequency    4662
drinking_in_a_row             5689
exercise                      1227
social_media                  4900
mental_health                 4398
hours_of_sleep                2662
sleep_place                   5562
grade                         3568
parent_emotional_abuse        6183
parent_physical_abuse         6186
parent_abuse_parent           6350
parent_uses_alcohol           6876
parent_mental_illness         6798
incarcerated_parent           6761
have_friend                   8926
parent_monitoring             9253
unfair_discipline_school      9520
ADHD                          9157
dtype: int64

In [12]:
data.head()

,age,gender,education_level,ride_drinking_driver,school_safety_concern,threatened_at_school,fight_count,school_fight_count,neighborhood_violence,sexual_violence,...,parent_emotional_abuse,parent_physical_abuse,parent_abuse_parent,parent_uses_alcohol,parent_mental_illness,incarcerated_parent,have_friend,parent_monitoring,unfair_discipline_school,ADHD
0,14 years old,Female,9th grade,4 or 5 times,2 or 3 days,0 times,0 times,0 times,No,0 times,...,NaN,Never,Never,No,Yes,No,Not sure,Sometimes,No,No
1,15 years old,Male,9th grade,0 times,0 days,0 times,1 time,1 time,No,0 times,...,Rarely,Rarely,Rarely,No,No,No,Agree,Always,No,Yes
2,16 years old,Male,11th grade,2 or 3 times,0 days,0 times,0 times,0 times,No,0 times,...,Sometimes,Rarely,Rarely,No,No,Yes,Agree,Most of the time,No,No
3,17 years old,Female,10th grade,0 times,2 or 3 days,0 times,0 times,0 times,No,0 times,...,Never,Never,Never,No,No,No,Disagree,Always,No,Yes
4,14 years old,Male,9th grade,0 times,0 days,0 times,2 or 3 times,0 times,No,0 times,...,Never,Never,Never,No,No,No,Agree,Always,No,No

In [13]:
for col in data.columns:
    print(col)
    print(data[col].unique().tolist())

age
['14 years old', '15 years old', '16 years old', '17 years old', '18 years old or older', nan, '12 years old or younger', '13 years old']
gender
['Female', 'Male', nan]
education_level
['9th grade', '11th grade', '10th grade', '12th grade', 'Ungraded or other grade', nan]
ride_drinking_driver
['4 or 5 times', '0 times', '2 or 3 times', '6 or more times', '1 time', nan]
school_safety_concern
['2 or 3 days', '0 days', '6 or more days', '1 day', nan, '4 or 5 days']
threatened_at_school
['0 times', '1 time', nan, '6 or 7 times', '2 or 3 times', '12 or more times', '10 or 11 times', '4 or 5 times', '8 or 9 times']
fight_count
['0 times', '1 time', '2 or 3 times', '6 or 7 times', '12 or more times', nan, '4 or 5 times', '10 or 11 times', '8 or 9 times']
school_fight_count
['0 times', '1 time', '2 or 3 times', '12 or more times', nan, '8 or 9 times', '4 or 5 times', '6 or 7 times', '10 or 11 times']
neighborhood_violence
['No', 'Yes', nan]
sexual_violence
['0 times', '2 or 3 times', '4 or 5 times', '1 time', nan, '6 or more times']
school_racism
['Never', 'Sometimes', 'Always', 'Rarely', 'Most of the time', nan]
school_bullying
['No', 'Yes', nan]
cyber_bullying
['No', 'Yes', nan]
feel_hopeless
['Yes', 'No', nan]
considered_suicide
['No', 'Yes', nan]
first_alcohol
['Never drank alcohol', '15 or 16 years old', '13 or 14 years old', '8 years old or younger', '9 or 10 years old', '11 or 12 years old', nan, '17 years old or older']
alcohol_frequency
['0 days', '1 or 2 days', 'All 30 days', '3 to 5 days', nan, '10 to 19 days', '6 to 9 days', '20 to 29 days']
hardcore_alcohol_frequency
['0 days', '1 day', '6 to 9 days', '2 days', '10 to 19 days', '20 or more days', nan, '3 to 5 days']
drinking_in_a_row
['Did not drink in past 30 days', '1 or 2 drinks', '6 or 7 drinks', nan, '10 or more drinks', '5 drinks', '4 drinks', '3 drinks', '8 or 9 drinks']
exercise
['0 days', '4 days', '7 days', '2 days', '5 days', '3 days', '1 day', nan, '6 days']
social_media
['Several times a day', 'A few times a week', 'More than once an hour', 'I do not use social media', 'About once an hour', 'About once a week', 'A few times a month', 'About once a day', nan]
mental_health
['Never', 'Sometimes', 'Rarely', nan, 'Most of the time', 'Always']
hours_of_sleep
['6 hours', '8 hours', '4 or less hours', '7 hours', '5 hours', '10 or more hours', '9 hours', nan]
sleep_place
['Home of parent or gaurdian', 'Somewhere else', 'Home of other people', 'Shelter or emergency housing', nan, 'Motel or hotel', 'Public place', 'No usual place']
grade
[nan, "Mostly D's", "Mostly C's", "Mostly F's", 'Not sure', "Mostly A's", "Mostly B's", 'None of these grades']
parent_emotional_abuse
[nan, 'Rarely', 'Sometimes', 'Never', 'Most of the time', 'Always']
parent_physical_abuse
['Never', 'Rarely', 'Most of the time', 'Sometimes', 'Always', nan]
parent_abuse_parent
['Never', 'Rarely', 'Sometimes', nan, 'Most of the time', 'Always']
parent_uses_alcohol
['No', 'Yes', nan]
parent_mental_illness
['Yes', 'No', nan]
incarcerated_parent
['No', 'Yes', nan]
have_friend
['Not sure', 'Agree', 'Disagree', 'Strongly agree', 'Strongly disagree', nan]
parent_monitoring
['Sometimes', 'Always', 'Most of the time', 'Rarely', 'Never', nan]
unfair_discipline_school
['No', 'Yes', nan]
ADHD
['No', 'Yes', nan]

In [14]:
def convert(df):
    data = df.copy()
    
    data['age'] = pd.to_numeric(data['age'].str.extract('(\d+)')[0])

    times_map = {
        '0 times': 0, '1 time': 1, '2 or 3 times': 2, '4 or 5 times': 4,
        '6 or 7 times': 6, '8 or 9 times': 8, '10 or 11 times': 10,
        '12 or more times': 12
    }
    
    days_map = {
        '0 days': 0, '1 day': 1, '2 days': 2, '3 to 5 days': 4,
        '6 to 9 days': 7, '10 to 19 days': 14, '20 to 29 days': 24,
        'All 30 days': 30
    }

    yes_no = {'Yes': 1, 'No': 0}

    freq_map = {
        'Never': 0, 'Rarely': 1, 'Sometimes': 2, 
        'Most of the time': 3, 'Always': 4
    }

    cols_times = ['ride_drinking_driver', 'threatened_at_school', 'fight_count', 'school_fight_count', 'sexual_violence']
    for col in cols_times:
        data[col] = data[col].map(times_map)
        
    cols_days = ['school_safety_concern', 'alcohol_frequency', 'hardcore_alcohol_frequency']
    for col in cols_days:
        data[col] = data[col].map(days_map)

    cols_yes_no = ['neighborhood_violence', 'school_bullying', 'cyber_bullying', 'feel_hopeless', 'parent_uses_alcohol',
                   'parent_mental_illness', 'incarcerated_parent', 'unfair_discipline_school', 'ADHD']
    for col in cols_yes_no:
        data[col] = data[col].map(yes_no)

    cols_freq = ['school_racism', 'mental_health', 'parent_emotional_abuse', 'parent_physical_abuse', 'parent_abuse_parent', 'parent_monitoring']
    for col in cols_freq:
        data[col] = data[col].map(freq_map)
    
    first_alcohol_map = {
        'Never drank alcohol': 0, '8 years old or younger': 8, '9 or 10 years old': 9, 
        '11 or 12 years old': 11, '13 or 14 years old': 13, '15 or 16 years old': 15, '17 years old or older': 17
    }
    data['first_alcohol'] = data['first_alcohol'].map(first_alcohol_map)
    
    drink_in_a_row = {
        'Did not drink in past 30 days': 0, '1 or 2 drinks': 1, '3 drinks': 3, '4 drinks': 4,
        '5 drinks': 5, '6 or 7 drinks': 6, '8 or 9 drinks': 8, '10 or more drinks': 10
    }
    data['drinking_in_a_row'] = data['drinking_in_a_row'].map(drink_in_a_row)
    
    exercise = {
        '0 days': 0, '1 day': 1, '2 days': 2, '3 days': 3,
        '4 days': 4, '5 days': 5, '6 days': 6, '7 days': 7
    }
    data['exercise'] = data['exercise'].map(exercise)
    
    social_media = {
        "I do not use social media": 0, "A few times a month": 1, "About once a week": 2, "A few times a week": 3,
        "About once a day": 4, "Several times a day": 5, "About once an hour": 6, "More than once an hour": 7
    }
    data['social_media'] = data['social_media'].map(social_media)

    sleep_hours = {
        '4 or less hours': 4,
        '5 hours': 5,
        '6 hours': 6,
        '7 hours': 7,
        '8 hours': 8,
        '9 hours': 9,
        '10 or more hours': 10
    }
    data['hours_of_sleep'] = data['hours_of_sleep'].map(sleep_hours)
        
    grades = {
        'Mostly A\'s': 4, 'Mostly B\'s': 3, 'Mostly C\'s': 2, 'Mostly D\'s': 1, 
        'Mostly F\'s': 0
    }
    data['grade'] = data['grade'].map(grades)

    feel_close = {
        'Strongly agree': 4, 'Agree': 3, 'Not sure': 2, 'Disagree': 1, 'Strongly disagree': 0
    }
    data['have_friend'] = data['have_friend'].map(feel_close)

    return data

<>:4: SyntaxWarning: invalid escape sequence '\d'
<>:4: SyntaxWarning: invalid escape sequence '\d'
C:\Users\chawi\AppData\Local\Temp\ipykernel_30352\3653777280.py:4: SyntaxWarning: invalid escape sequence '\d'
  data['age'] = pd.to_numeric(data['age'].str.extract('(\d+)')[0])

In [15]:
def clean(df):
    data = df.copy()
    data = data.dropna(subset=['grade'])

    med = ['age', 'ride_drinking_driver', 'school_safety_concern', 'threatened_at_school', 'fight_count', 'school_fight_count',
           'school_racism', 'first_alcohol', 'alcohol_frequency', 'hardcore_alcohol_frequency', 'drinking_in_a_row',
           'exercise', 'social_media', 'mental_health', 'hours_of_sleep', 'parent_emotional_abuse', 'parent_physical_abuse',
           'parent_abuse_parent', 'parent_uses_alcohol', 'parent_mental_illness', 'incarcerated_parent', 'have_friend',
           'parent_monitoring', 'unfair_discipline_school', 'ADHD']
    for i in med:
        data[i] = data[i].fillna(data[i].median())

    for col in data.select_dtypes(include='number').columns:
        data[col] = data[col].fillna(-1)

    # All other columns
    for i in data.columns[data.isnull().any()].tolist():
        data[i] = data[i].fillna('unknown')
    
    return data

In [16]:
converted_data = convert(data)
cleaned_data = clean(converted_data)

In [17]:
cleaned_data

,age,gender,education_level,ride_drinking_driver,school_safety_concern,threatened_at_school,fight_count,school_fight_count,neighborhood_violence,sexual_violence,...,parent_emotional_abuse,parent_physical_abuse,parent_abuse_parent,parent_uses_alcohol,parent_mental_illness,incarcerated_parent,have_friend,parent_monitoring,unfair_discipline_school,ADHD
1,15.0,Male,9th grade,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,1.0,1.0,0.0,0.0,0.0,3.0,4.0,0.0,1.0
2,16.0,Male,11th grade,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,1.0,1.0,0.0,0.0,1.0,3.0,3.0,0.0,0.0
3,17.0,Female,10th grade,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,0.0,1.0
4,14.0,Male,9th grade,0.0,0.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,4.0,0.0,0.0
5,16.0,Male,9th grade,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,2.0,3.0,0.0,0.0,0.0,0.0,4.0,4.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20096,15.0,Male,9th grade,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,0.0,0.0
20099,15.0,Male,9th grade,0.0,0.0,0.0,0.0,0.0,1.0,-1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,0.0,0.0
20100,15.0,Male,9th grade,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,0.0,0.0
20101,16.0,Male,9th grade,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,0.0,0.0
20102,15.0,Female,9th grade,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,0.0,0.0

In [19]:
cleaned_data.info()

<class 'pandas.DataFrame'>
Index: 15694 entries, 1 to 20102
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   age                         15694 non-null  float64
 1   gender                      15694 non-null  str
 2   education_level             15694 non-null  str
 3   ride_drinking_driver        15694 non-null  float64
 4   school_safety_concern       15694 non-null  float64
 5   threatened_at_school        15694 non-null  float64
 6   fight_count                 15694 non-null  float64
 7   school_fight_count          15694 non-null  float64
 8   neighborhood_violence       15694 non-null  float64
 9   sexual_violence             15694 non-null  float64
 10  school_racism               15694 non-null  float64
 11  school_bullying             15694 non-null  float64
 12  cyber_bullying              15694 non-null  float64
 13  feel_hopeless               15694 non-null  float64
 14  considered_suicide          15694 non-null  str
 15  first_alcohol               15694 non-null  float64
 16  alcohol_frequency           15694 non-null  float64
 17  hardcore_alcohol_frequency  15694 non-null  float64
 18  drinking_in_a_row           15694 non-null  float64
 19  exercise                    15694 non-null  float64
 20  social_media                15694 non-null  float64
 21  mental_health               15694 non-null  float64
 22  hours_of_sleep              15694 non-null  float64
 23  sleep_place                 15694 non-null  str
 24  grade                       15694 non-null  float64
 25  parent_emotional_abuse      15694 non-null  float64
 26  parent_physical_abuse       15694 non-null  float64
 27  parent_abuse_parent         15694 non-null  float64
 28  parent_uses_alcohol         15694 non-null  float64
 29  parent_mental_illness       15694 non-null  float64
 30  incarcerated_parent         15694 non-null  float64
 31  have_friend                 15694 non-null  float64
 32  parent_monitoring           15694 non-null  float64
 33  unfair_discipline_school    15694 non-null  float64
 34  ADHD                        15694 non-null  float64
dtypes: float64(31), str(4)
memory usage: 4.3 MB